# Linear Algebra: Systems of equations

* Many problems require finding solutions to systems of linear equations.
* Example problem: a circuit of resistors.
* Other examples include solving coupled ODEs with multiple variables, such as the skydiver problem with side wind, or a couple system of nuclear or chemical reactions, a so-called network.
* We will solve linear systems of equations via Gaussian elimination.

## Circuit of resistors
### The problem
A circuit of resistors, all with the same resistance, connects ground with a power rail at the voltage $V_\mathrm{Rail}$ as shown in this diagram: ![Resistor](../images/ResistorCircuit.jpg)

A common problem in physics may involve that we  want to know the voltages at each of the junctions, $V_1, V_2, \dots$ when $V_\mathrm{Rail}$ is given and all resistors have the same  resistance $R$.

The physics of this problem involves two aspects:
1. Kirchhoff current law (a conservation law): The sum of all currents at any junction points must be zero.
2. Ohm's law: The relation between current $I$, voltage $V$ and resistance is $$R = \frac{V}{I}$$

These fundamental electricitiy problems can be best understood in terms of the water analogy. 

### Set up equations
* The current between two junctions is given by the voltage difference divided by the resistance (Ohm's law).
* For each junction the sum of the currents into (or out of) the junction must be zero, i.e. in the voltage differences must contain the voltage at the junction with the same sign 
* Since the resistance is the same for all resistors it cancels and I we can ommit it right from the beginning. 
* $V_\mathrm{Rail} = 5 \mathrm{V}$

The sum of the voltage differences at each junction is as follows:

- v3: $(V_3 - V_4) + (V_3 -5) + (V_3 - V_1) = 0$
- v2: $(V_2 - V_4) + (V_2 - 0) + (V_2 - V_1) = 0$
- v1: $(V_1 - V_3) + (V_1 - 0) + (V_1 - V_2) + (V_1 - V_4) = 0$
- v4: $(V_4 - 5) + (V_4 - V_3) + (V_4 - V_2) + (V_4 - V_1) = 0$

You will need to simplify the equations in the four variables $V_1, V_2, V_3$ and $V_4$ and then solve the linear system of equations, which you are asked to do in Assignment 3.

### Another example
More generally you will end up with a coupled system of linear equations like this:

$$\begin{eqnarray*}
 2 v_1 + 2 v_2 + 3 v_3 &= 1 \\ 
 4 v_1 + 5 v_2 + 5 v_3 &= 4 \\
 v_1 + 2 v_2 + v_3 &= 2
\end{eqnarray*}$$

In this case you have three equations, three variables - this is solvable (unless the equations are not independent).  

## Linear Algebra

### Resources

* Linear Algebra:
    * Chapter 6 in [Newman: Computational Physics _with Python_](http://www-personal.umich.edu/~mejn/computational-physics)
    * many resources on the internet, e.g. [Linear Algebra Primer](https://plot.ly/python/linear-algebra/)
* [Array creation in Python](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html)
* more Python programming with arrays for example in Chapter 5 in [Langtangen: A Primer on Scientific Programming with Python](http://voyager.library.uvic.ca/vwebv/holdingsInfo?searchId=4972&recCount=25&recPointer=13&bibId=2865846) (available as ebook from the UVic library)


### Review of some basics
Product of arrays and vectors:

In [1]:
a = [ 1, 2, 3] 
b = [4, 5, 6]
a+b

[1, 2, 3, 4, 5, 6]

In [2]:
import numpy as np
u = np.array(a)
v = np.array(b)
u*v

array([ 4, 10, 18])

This is an element-wise operation and the result is again an error. This is not any of the vector operations that we are familiar. 

In [3]:
def dot_prod(u,v):
    '''
    vector product
    
    input: two vectors of equal lenght
    output: scalar 
        
    '''
    if len(u) is not len(v): 
        print("Error: vectors do not have same lenght.")
    uv_prod = 0
    for i in range(len(u)):
        uv_prod += u[i]*v[i]
    return uv_prod

dot_prod(u,v)

32

The dot product is also provided by numpy:

In [4]:
import numpy as np
np.dot(u,v)

32

### Gaussian elimination

The above system of equations can be written as  $\vec{u} = \matrix{A} \cdot \vec{v}$ with 

$$
\matrix{A} = \pmatrix{ 2 & 2 & 3 \\ 
                       4 & 5 & 5 \\
                       1 & 2 & 1 }
$$

and $$\vec{u} = \pmatrix{1\\4\\2}.$$ The vector $\vec{v}$ is the desired solution to the coupled system of linear equations given above. [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination) is a systematic method to accomplish this.

Recall the important notion from linear algebra that the solution will not change if
* we multiply an equation by any number, or if
* we add and substract equations from each other. 

With this a scheme that finds numerically $vec{v}$ by using these rules looks like this:

1. divide 1$^\mathrm{st}$ equation by $a_{11} (= 2)$:
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
 4 v_1 + 5 v_2 + 5 v_3 &= 4 \\
 v_1 + 2 v_2 +  v_3 &= 2
\end{eqnarray*}$$
2. substract $a_{21} (= 4)$ times 1$^\mathrm{st}$ equation from 2$^\mathrm{nd}$ equation:
$$\begin{eqnarray*}
 v_1 + 1 v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
                   1 v_2 - 1 v_3 &= 2 \\
 v_1 + 2 v_2 + 1 v_3 &= 2
\end{eqnarray*}$$
3. substract $a_{31} (= 1)$ times 1$^\mathrm{st}$ equation from 3$^\mathrm{rd}$ equation:
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
       v_2 -             v_3 &= 2 \\
       v_2 - \frac{1}{2} v_3 &= \frac{3}{2}
\end{eqnarray*}$$
the result is that the first column disappeared in all but the first row
4. repeat for remaining set of equations excluding first row
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
       v_2 -             v_3 &= 2 \\
             \frac{1}{2} v_3 &= -\frac{1}{2}
\end{eqnarray*}$$
5. repeat until entire set of equations is in triangular form and last equation has only one variable
6. backsubstitution: solve last equation, substitute into last-but-one, solve, substitute etc.

The solution should be $$\vec{v} = \pmatrix{1 \\ 1 \\ -1 }$$ 

Let's see how this can be implemented:

In [78]:
# reset A
ar1=array([2,2,3])
ar2=array([4,5,5])
ar3=array([1,2,1])
A=array([ar1,ar2,ar3])
u = array([1,4,2])
print(A,u)

[[2 2 3]
 [4 5 5]
 [1 2 1]] [1 4 2]


I need to apply the same operation to the right-hand side, i.e. $\vec{u}$. The easiest way to do this is to add $\vec{u}$ as an additional column to my working copy `AA` of the matrix `A`. I can use numpy `vstack` for that again, but add to `A.T` instead of `A`, and then take the transpose again:

In [79]:
AA = vstack((A.T,u)).T      # vstack is a numpy function!
print(AA)

[[2 2 3 1]
 [4 5 5 4]
 [1 2 1 2]]


I will start by performing the first step by hand. That will give me some ideas how to compactify and generalize the algorithm into a routine.

1. divide 1$^\mathrm{st}$ equation by $a_{11} (= 2)$:

In [62]:
# I will be working with rows:
i=0
AA[i] = AA[i]/AA[i,0]

In [63]:
AA

array([[1, 1, 1, 0],
       [4, 5, 5, 4],
       [1, 2, 1, 2]])

Here we can see a problem. The $3^\mathrm{rd}$ element in the first row should be $1.5$ and the last should be $0.5$. The matrix `AA` has data type`dtype('int64')`. It needs to be a float. I must check for this situation and change the dtype to float. 

In [80]:
if not 'float' in str(AA.dtype): # there are different types of floats
    AA=AA.astype(float) 
    # and integer data types, e.g. int32, int64
    # and this way I am checking in the most general way
    # I will also not overwrite A but create a new working array with the 
    # required float data type
print(AA)

[[ 2.  2.  3.  1.]
 [ 4.  5.  5.  4.]
 [ 1.  2.  1.  2.]]


In [81]:
#  now try again
i=0
AA[i] = AA[i]/AA[i,0]

In [82]:
AA

array([[ 1. ,  1. ,  1.5,  0.5],
       [ 4. ,  5. ,  5. ,  4. ],
       [ 1. ,  2. ,  1. ,  2. ]])

In [83]:
# This loop allows me to perform step 2 and 3: 
i=0
for j in range(i,len(A)): print(j)

0
1
2


In [84]:
i=0
for j in range(i+1,len(AA)):
    print (i,j)
    AA[j] -= AA[j,0]*AA[i]
    print(AA[j])

0 1
[ 0.  1. -1.  2.]
0 2
[ 0.   1.  -0.5  1.5]


In [85]:
AA

array([[ 1. ,  1. ,  1.5,  0.5],
       [ 0. ,  1. , -1. ,  2. ],
       [ 0. ,  1. , -0.5,  1.5]])

Now, I will repeat this with `i=1` [I discover that of course the second index in `AA[j,0]` needs to be updated as well

In [87]:
i=1
AA[i] = AA[i]/AA[i,i]
for j in range(i+1,len(AA)):
    print (i,j)
    AA[j] -= AA[j,i]*AA[i]
    print(AA[j])

In [88]:
# check that AA is still what they should be, if not 
# reset by going back to the cell:
AA

array([[ 1. ,  1. ,  1.5,  0.5],
       [ 0. ,  1. , -1. ,  2. ],
       [ 0. ,  0. ,  1. , -1. ]])

Executing again with `i=2` gives the desired diagonal form.

Now we just need to implement the back-substitution

In [89]:
BB=copy(AA)
m  = len(A)-1     # highest row/col index (we do only square matrices)
v  = zeros(m+1,float) 
u  = BB.T[-1]       # extract RHS
AA = delete(BB,m+1,1) # recover diagonalized coefficient matrix  

In [75]:
v[m] = u[m]

In [76]:
v[m-1] = u[m-1] - v[m]*AA[m-1,m]

In [46]:
v

array([ 1.,  1., -1.])

In [44]:
v[m-2] = u[m-2] - v[m]*AA[m-2,m] - v[m-1]*AA[m-2,m-1]

This can be made into a loop. However, I realize that this can be generalized in the following way. If we go backwards and initialize `v` as `zeros()` then I may just always subtract from the u component the dot product of `v` and the respective row of `AA`:

In [45]:
for j in range(m,-1,-1): print(j)

2
1
0


In [46]:
# reset AA and u:
AA,u

(array([[ 1. ,  1. ,  1.5],
        [ 0. ,  1. , -1. ],
        [ 0. ,  0. ,  1. ]]), array([ 0.5,  2. , -1. ]))

In [91]:
for j in range(m,-1,-1):
    v[j] = u[j] - v.dot(AA[j])

In [92]:
v

array([ 1.,  1., -1.])

### Solution with numpy.linalg

As an example we define a matrix $\matrix{A}$ and carry out the dot product with a vector $vec{u}$. 

In [12]:
import numpy as np
A=np.matrix([[1,2],[1,1]])
u=np.array([3,1])
A.dot(u)

matrix([[5, 4]])

$ \matrix{A} \cdot \vec{u} = \vec{v}$, given $\vec{v}$ and $\matrix{A}$ what is $\vec{u}$?

In [13]:
v=np.array([5,4])
np.linalg.solve(A,v)

array([ 3.,  1.])