# Linear Algebra: Systems of equations

* Many problems require finding solutions to systems of linear equations.
* Example problem: a circuit of resistors.
* Other examples include solving coupled ODEs with multiple variables, such as the skydiver problem with side wind, or a couple system of nuclear or chemical reactions, a so-called network.
* We will solve linear systems of equations via Gaussian elimination.

## Circuit of resistors
### The problem
A circuit of resistors, all with the same resistance, connects ground with a power rail at the voltage $V_\mathrm{Rail}$ as shown in this diagram: ![Resistor](../images/ResistorCircuit.jpg)

A common problem in physics may involve that we  want to know the voltages at each of the junctions, $V_1, V_2, \dots$ when $V_\mathrm{Rail}$ is given and all resistors have the same  resistance $R$.

The physics of this problem involves two aspects:
1. Kirchhoff current law (a conservation law): The sum of all currents at any junction points must be zero.
2. Ohm's law: The relation between current $I$, voltage $V$ and resistance is $$R = \frac{V}{I}$$

These fundamental electricitiy problems can be best understood in terms of the water analogy. 

### Set up equations
* The current between two junctions is given by the voltage difference divided by the resistance (Ohm's law).
* For each junction the sum of the currents into (or out of) the junction must be zero, i.e. in the voltage differences must contain the voltage at the junction with the same sign 
* Since the resistance is the same for all resistors it cancels and I we can ommit it right from the beginning. 
* $V_\mathrm{Rail} = 5 \mathrm{V}$

Let's start with the junction point 3:

- v3: $(V_3 - V_4) + (V_3 -5) + (V_3 - V_1) = 0$

You will complete the other equations in the Lab. You will simplify the equations in the four variables $V_1, V_2, V_3$ and $V_4$. 

### Another example
More generally you will end up with a coupled system of linear equations like this:

$$\begin{eqnarray*}
 2 v_1 + 2 v_2 + 3 v_3 &= 1 \\ 
 4 v_1 + 5 v_2 + 5 v_3 &= 4 \\
 v_1 + 2 v_2 + v_3 &= 2
\end{eqnarray*}$$

In this case you have three equations, three variables - this is solvable (unless the equations are not independent).  

## Linear Algebra

### Resources

* Linear Algebra:
    * Chapter 6 in [Newman: Computational Physics _with Python_](http://www-personal.umich.edu/~mejn/computational-physics)
    * Chapter 4.4 in [Cunningham: Python in 24 hours](http://voyager.library.uvic.ca/vwebv/holdingsInfo?searchId=5015&recCount=25&recPointer=17&bibId=3208444) (available as ebook from the UVic library)
* [Array creation in Python](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html)
* more Python programming with arrays for example in Chapter 5 in [Langtangen: A Primer on Scientific Programming with Python](http://voyager.library.uvic.ca/vwebv/holdingsInfo?searchId=4972&recCount=25&recPointer=13&bibId=2865846) (available as ebook from the UVic library)


### Review of some basics
Product of arrays and vectors:

In [21]:
a = [ 1, 2, 3] 
b = [4, 5, 6]
a+b

[1, 2, 3, 4, 5, 6]

In [22]:
import numpy as np
u = np.array(a)
v = np.array(b)
u*v

array([ 4, 10, 18])

This is an element-wise operation and the result is again an error. This is not any of the vector operations that we are familiar. 

In [23]:
def dot_prod(u,v):
    '''
    vector product
    
    input: two vectors of equal lenght
    output: scalar 
        
    '''
    if len(u) is not len(v): 
        print("Error: vectors do not have same lenght.")
    uv_prod = 0
    for i in range(len(u)):
        uv_prod += u[i]*v[i]
    return uv_prod

dot_prod(u,v)

32

Enter this method into your own library ....

The dot product is also provided by numpy:

In [24]:
import numpy as np
np.dot(u,v)

32

### Gaussian elimination

The above system of equations can be written as  $\vec{u} = \matrix{A} \cdot \vec{v}$ with 

$$
\matrix{A} = \pmatrix{ 2 & 2 & 3 \\ 
                       4 & 5 & 5 \\
                       1 & 2 & 1 }
$$

and $$\vec{u} = \pmatrix{1\\4\\2}.$$ The vector $\vec{v}$ is the desired solution to the coupled system of linear equations given above. [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination) is a systematic method to accomplish this.

Recall the important notion from linear algebra that the solution will not change if
* we multiply an equation by any number, or if
* we add and substract equations from each other. 

With this a scheme that finds numerically $vec{v}$ by using these rules looks like this:

1. divide 1$^\mathrm{st}$ equation by $a_{11} (= 2)$:
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
 4 v_1 + 5 v_2 + 5 v_3 &= 4 \\
 v_1 + 2 v_2 +  v_3 &= 2
\end{eqnarray*}$$
2. substract $a_{21} (= 4)$ times 1$^\mathrm{st}$ equation from 2$^\mathrm{nd}$ equation:
$$\begin{eqnarray*}
 v_1 + 1 v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
                   1 v_2 - 1 v_3 &= 2 \\
 v_1 + 2 v_2 + 1 v_3 &= 2
\end{eqnarray*}$$
3. substract $a_{31} (= 1)$ times 1$^\mathrm{st}$ equation from 3$^\mathrm{rd}$ equation:
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
       v_2 -             v_3 &= 2 \\
       v_2 - \frac{1}{2} v_3 &= \frac{3}{2}
\end{eqnarray*}$$
the result is that the first column disappeared in all but the first row
4. repeat for remaining set of equations excluding first row
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
       v_2 -             v_3 &= 2 \\
             \frac{1}{2} v_3 &= -\frac{1}{2}
\end{eqnarray*}$$
5. repeat until entire set of equations is in triangular form and last equation has only one variable
6. backsubstitution: solve last equation, substitute into last-but-one, solve, substitute etc.

The solution should be $$\vec{v} = \pmatrix{1 \\ 1 \\ -1 }$$ 

### Solution with numpy.linalg

As an example we define a matrix $\matrix{A}$ and carry out the dot product with a vector $vec{u}$. 

In [25]:
import numpy as np
A=np.matrix([[1,2],[1,1]])
u=np.array([3,1])
A.dot(u)

matrix([[5, 4]])

$ \matrix{A} \cdot \vec{u} = \vec{v}$, given $\vec{v}$ and $\matrix{A}$ what is $\vec{u}$?

In [26]:
v=np.array([5,4])
np.linalg.solve(A,v)

array([3., 1.])